- tcms/testplans/models.py
- simplify the code to make it more readable
- reduce the number of SQL queries
- reduce the size of data set returned from database server
- reduce the complexity of SQL then the cost of execution in database server
Change-Id: I3ab56c0d395a6c11b3205aa4e8168213989c01e7
> refactor TestPlan.get_case_sortkey

- Makefile
- tcms/core/contrib/linkreference/forms.py
- tcms/core/contrib/linkreference/models.py
- tcms/core/contrib/linkreference/views.py
- tcms/core/db.py
- tcms/integration/djqpid/producer.py
- tcms/report/data.py
- tcms/settings/test.py
- tcms/testcases/models.py
- tcms/testcases/views.py
- tcms/testplans/forms.py
- tcms/testplans/models.py
- tcms/testplans/views.py
- tcms/testruns/helpers/serializer.py
- tcms/testruns/models.py
- tcms/testruns/views.py
- tcms/xmlrpc/__init__.py
- tcms/xmlrpc/serializer.py
First fix all flake8 errors and warnings. Then I want to refactor the Makefile to not return an error about missing rpm command in Travis.
> Travis CI improvements

- tcms/core/ajax.py
- tcms/core/contrib/plugins_support/processors.py
- tcms/profiles/views.py
- tcms/report/tests.py
- tcms/testcases/models.py
- tcms/testruns/models.py
This is based on atodorov's patch "Fix flake8 blank lines" and fixes
more others.
> Fix code style errors checked by flake8

- MANIFEST.in
- setup.cfg
- setup.py
- Add more package information into setup.py.
- Remove line from MANIFEST.in that includes non-existent
tcms/core/lib/.
- Do not include docs/target in source distribution package.
- Include tests/ in source distribution package.
> Refine distribution package

- docs/source/contribution.rst
Rewrite part of document, fix typos and grammar errors.
> Refine contribution.rst

- tcms/testruns/models.py
> Remove max_length from IntegerField

- CHANGELOG.rst
- nitrate.spec
- requirements/base.txt
- tcms/templates/plan/edit.html
Upgrade to latest version of django-tinymce and remove left over tiny_mce.js reference in template.
cc @tkdchen
> Upgrade to django-tinymce 2.4.0 

- tcms/core/migrations/0002_add_initial_data.py
- tcms/management/migrations/0002_add_initial_data.py
- tcms/testcases/migrations/0003_add_initial_data.py
- tcms/testplans/migrations/0002_add_initial_data.py
- tcms/testruns/migrations/0002_add_initial_data.py
- tcms/testruns/migrations/0003_testrun_estimated_time_remove_max_length.py
> Remove unused imports to make flake8 happy

- tcms/core/migrations/0001_django_comments__object_pk.py
> Don't use RawSQL in migrations

- docs/source/set_dev_env_with_vagrant.rst
> Update doc to use latest Vagrantfile

- .travis.yml
- MANIFEST.in
- Makefile
- Vagrantfile
- contrib/conf/nitrate-apidoc.conf
- nitrate.spec
- setup.cfg
- setup.py
Major changes within in this PR aim to simplify and fix issues within ``setup.py``, ``nitrate.spec`` and ``Makefile``.
> More clean

- Makefile
- tcms/fixtures/cases-to-import.xml
- tcms/management/models.py
- tcms/settings/common.py
- tcms/testplans/tests.py
- tcms/testplans/views.py
Following two issues are also fixed
- add missing XML version setting
- fix error testcase creation when importing from XML document exported
previously
> fix testplans unittests and all pass

- requirements/devel.txt
- tests/__init__.py
Factories for models are created and placed into tests/__init__.py.
Using it in tests, do following
import tests
case = tests.TestCaseFactory()
> Use factory_boy to create fixtures

- Makefile
- setup.py
> Fix 155, Don't install files under etc

- tcms/testcases/forms.py
- tcms/testcases/tests.py
- tcms/testcases/views.py
- tcms/testruns/views.py
Replace part of ``REQUEST`` in app ``testcases``, and add tests.
> Replace part REQUEST

- tcms/core/contrib/comments/views.py
- tcms/static/js/tcms_actions.js
- tcms/templates/case/get_details_case_run.html
- tcms/testruns/views.py
- tcms/urls.py
Clean code in ``core.contrib.comments``.
Relative to #173 as well.
> Clean comments

- tcms/profiles/tests.py
- tcms/profiles/views.py
> Replace REQUEST with GET or POST in profiles.views.bookmark

- tcms/templates/case/get_details_review.html
> Fix: use POST to delete comment from reviewing cases

- tcms/management/tests.py
- tcms/management/views.py
- tcms/static/js/management_actions.js
- tcms/templates/environment/group_edit.html
As of this PR, all ``request.REQUEST``s have been replaced.
> Cleanup environment groups properties

- tcms/core/ajax.py
- tcms/core/tests/test_ajax.py
- tcms/core/tests/test_views.py
- tcms/static/js/testrun_actions.js
This PR also contains fixes in #178  from contributor with update.
> Replace request core ajax

- tcms/core/tests/test_views.py
- tcms/testruns/tests.py
- tcms/tests/__init__.py
This base class contains pre-created test run and case runs.
> New base test case class BaseCaseRun

- tcms/testruns/data.py
- tcms/testruns/models.py
- tcms/testruns/sqls.py
- tcms/testruns/tests.py
- tcms/testruns/views.py
Replace ``REQUEST`` in ``new`` view method.
Cherry-pick and add tests to changes that convert raw SQL to ORM calls, that is committed by @atodorov Thanks.
> Refine new run

- tcms/templates/run/clone.html
- tcms/templates/run/clone_multiple.html
- tcms/testruns/models.py
- tcms/testruns/tests.py
- tcms/testruns/views.py
- tcms/tests/__init__.py
- Add tests for new and clone view method
- Fixed wrong HTML in template
> Replace REQUEST in new and clone view method in testruns

- tcms/testruns/tests.py
- tcms/testruns/views.py
- tcms/tests/__init__.py
> Replace another REQUESTs in testruns.views

- tcms/core/utils/obj2dict.py
> Remove unused obj2dict.py

- requirements/base.txt
> kobo can be installed from PyPI

- requirements/base.txt
> Upgrade django-tinymce to 2.6.0

- tcms/core/ajax.py
- tcms/core/contrib/linkreference/views.py
- tcms/integration/bugzilla/signals/bugs.py
- tcms/integration/bugzilla/task.py
- tcms/search/forms.py
- tcms/testcases/views.py
- tcms/testplans/forms.py
- tcms/testplans/views.py
> Fix deprecated except statement

- requirements/base.txt
> Upgrade kobo to 0.7.0

- tcms/testcases/views.py
> Fix wrong name from_rlan

- tcms/templates/case/all.html
- tcms/templates/plan/all.html
- tcms/testcases/views.py
> Fix plans and cases search

- docs/source/installing_in_virtualenv.rst
> Fix settings value in doc for installing with Apache (virtualenv)

- tcms/core/contrib/linkreference/views.py
- tcms/core/files.py
- tcms/management/views.py
- tcms/profiles/views.py
- tcms/testcases/views.py
- tcms/testplans/views.py
- tcms/testruns/views.py
> Use permission_required

- Makefile
- setup.cfg
- tox.ini
> Run flake8 from tox

- tcms/core/files.py
* If no plan or case ID is passed, method should not proceed to handle
uploaded file.
* Simplify checking file existance.
* Simplify code to avoid catching exception.
> Refactor upload_file

- tcms/core/ajax.py
> Show status name rather than id in case run change log

- tcms/testcases/signals.py
> Remove unused class EditCaseNotifyThread

- tox.ini
> Do not install Nitrate for flake8 testenv

- tcms/templates/plan/get_review_cases.html
> Fix link case url in reviewing cases tab

- tcms/static/js/testplan_actions.js
> Show product versions properly when open /plan/new/

- .coveragerc
> Skip 100% covered files in coverage report

- .readthedocs.yml
> Specify to use Python 3.5 for readthedocs

- README.rst
> Add readthedocs doc badge

- MANIFEST.in
> Fix MANIFEST.in to include missing files

- tcms/report/data.py
> Fix wrong six.moves.imap in custom report

- tcms/testruns/views.py
- tcms/xmlrpc/api/testcase.py
- tcms/xmlrpc/api/testplan.py
- tcms/xmlrpc/api/testrun.py
> Remove some unnessesary single raise statements

- tcms/static/js/testplan_actions.js
- tcms/testplans/views.py
Signed-off-by: Chenxiong Qi <cqi@redhat.com>
> Fix: Tree view shows spinner and never loads (#290)

- tcms/static/js/tcms_actions.js
- tcms/static/js/testplan_actions.js
> Fix "Update versions failed" when create a plan from am empty db

- setup.cfg
> Generate coverage HTML report as well

- tcms/core/utils/validations.py
- tcms/testcases/models.py
- tcms/testcases/tests/test_models.py
- tcms/testcases/views.py
- tcms/testplans/forms.py
- tcms/testplans/tests/test_forms.py
- tcms/testruns/helpers/serializer.py
- tcms/testruns/tests/test_serializer.py
- tcms/testruns/views.py
- tcms/xmlrpc/api/testcase.py
- tcms/xmlrpc/api/testplan.py
- tcms/xmlrpc/api/testrun.py
- tcms/xmlrpc/tests/test_testcase.py
- tcms/xmlrpc/tests/test_testplan.py
- tcms/xmlrpc/tests/test_testrun.py
Some calls to builtin function map break some features in Python 3 due
to map returns a generator instead of list. Tests are added accordingly.
Fixes #313
> Fix some calls to function map

- tcms/testplans/tests/test_forms.py
> Add missing test in 93ee243

- README.rst
> Update README for use of vagrant machine

- tcms/core/views/search.py
- tox.ini
> Fix flake8 errors and ignore W504

- tcms/settings/common.py
> Remove old bug system option from settings

- tcms/core/utils/__init__.py
- tcms/testruns/models.py
> Use str.isdigit instead of custom is_int

- setup.py
- tox.ini
> Django 1.11 is the minimum version to work with

- tcms/testcases/views.py
- tcms/xmlrpc/serializer.py
- tcms/xmlrpc/tests/test_product.py
> Minor changes

- tcms/integration/issuetracker/task.py
> Fix issuetracker async task

- tcms/settings/common.py
> Fix default release version in settings

- tcms/core/task.py
> Fix celery detection in core/task.py

- .travis.yml
- setup.py
- tcms/core/tests/test_core.py
- tox.ini
> Work with Python 3.7

- tcms/settings/common.py
- tcms/settings/devel.py
- tcms/settings/product.py
> Clean settngs modules

- .travis.yml
- contrib/travis-ci/Dockerfile
- contrib/travis-ci/runtests.sh
- tcms/core/tests/test_files.py
- tcms/management/tests.py
- tcms/management/views.py
- tcms/settings/test.py
- tcms/testruns/tests/test_views.py
- tox.ini
> Run tests with different database backends

- tcms/static/style/base.css
Fix broken groups SELECT layout in page /admin/auth/user/id/change/.
Make permissions SELECT height higher.
> Adjust SELECT layout and height in admin pages

- contrib/ansible/testenv/roles/devenv/tasks/main.yml
- docs/source/configuration.rst
- tcms/core/management/commands/setdefaultperms.py
- tcms/core/tests/test_commands.py
> Rewrite script as a command to set permissions to default groups

- Makefile
> Runserver simply with different db engine

- .coveragerc
- tcms/core/db.py
- tcms/core/tests/test_core.py
- tcms/report/data.py
- tcms/report/sqls.py
- tcms/report/templatetags/report_stats.py
- tcms/report/tests.py
- tcms/report/views.py
- tcms/settings/common.py
- tcms/static/style/base.css
- tcms/templates/report/build.html
- tcms/templates/report/case_runs_status_subtotal.html
- tcms/templates/report/custom_details_status_matrix.html
- tcms/templates/report/overview.html
> Fix report sqls for pgsql

- tcms/templates/environment/group_edit.html
> Fix multiple select in environment group edit page

- setup.py
> Set zip_safe to False

- tcms/core/utils/raw_sql.py
> Reformat some raw SQLs

- src/tcms/testruns/models.py
> Remove unused methods from TestCaseRunManager

- docs/source/configuration.rst
- setup.py
- src/static/style/base.css
- src/tcms/auth/backends.py
- src/tcms/auth/views.py
- src/tcms/core/context_processors.py
- src/tcms/profiles/urls.py
- src/tcms/settings/common.py
- src/templates/registration/login.html
- src/templates/tcms_base.html
It is possible to log into Nitrate via 3rd party authentication backends, e.g. Fedora or Google, etc.
Fixes #44 #153
> Multiple auth backends

- .coveragerc
* Remove commented out lines
* Remove invalid lines from omit
* Omit Python files that are not necessary to be evaluated
> Clean .coveragerc

- README.rst
> Quay.io badge should link to the repo

- src/tcms/core/ajax.py
Happens in /case/N/ page.
Fixes #387
> Fix error while typing new tag to get tag info

- docs/source/install/docker.rst
This patch also reword part of the document to make it more usable.
> Fix incorrect docker-exec commands in docker.rst

- docker/released/product.py
- src/tcms/settings/product.py
> Remove wrong TESTOPIA_XML_VERSION from product.py

- src/tcms/report/data.py
- src/tcms/report/sqls.py
This is a similar fix with the solution of issue #394.
> Fix error when select a build to generate report By Case-Run Tester

- src/tcms/report/data.py
- src/tcms/report/sqls.py
This is a similar fix with the solution of issue #394.
> Fix testing report By Plan's Tag

- docker/released/Dockerfile
> Expose volumn for uploads in release docker image

- .travis.yml
- README.rst
- setup.py
- tox.ini
> Drop Django 1.11

- Makefile
- contrib/conf/wsgi-venv.conf
- docker/dev/Dockerfile
- docker/released/Dockerfile
> Upgrade base image to Fedora 30

- .travis.yml
- README.rst
- setup.py
> Add Django 2.2 to Travis-CI

- src/static/js/tcms_actions.js
- src/static/js/testrun_actions.js
> Remove debug info from JS

- src/static/js/tcms_actions.js
> Use DOM API to construct select option elements

- Makefile
- docker/released/Dockerfile
> Set version properly in released image

- docs/source/install/index.rst
> Update document for running from a released image

- setup.py
> Use latest version of pytest

- setup.py
> Upgrade django-contrib-comments to 1.9.1

- Makefile
> Allow specifying release version for up-release-container target

- src/tcms/testcases/views.py
- src/tcms/testruns/ajax.py
- src/tcms/xmlrpc/filters.py
- src/tests/__init__.py
- src/tests/core/test_core.py
- src/tests/core/test_views.py
- src/tests/test_management.py
- src/tests/testcases/test_views.py
- src/tests/testplans/test_views.py
- src/tests/testruns/test_views.py
- src/tests/xmlrpc/test_filters.py
> Import http status code from correct module

- src/tcms/xmlrpc/filters.py
> Add missing imports

- src/tests/__init__.py
- src/tests/core/test_files.py
- src/tests/core/test_views.py
- src/tests/issuetracker/test_services.py
- src/tests/test_management.py
- src/tests/test_search.py
- src/tests/testcases/test_models.py
- src/tests/testcases/test_views.py
- src/tests/testplans/test_models.py
- src/tests/testplans/test_views.py
- src/tests/testruns/test_data.py
- src/tests/testruns/test_models.py
- src/tests/testruns/test_serializer.py
- src/tests/testruns/test_views.py
- src/tests/xmlrpc/test_product.py
- src/tests/xmlrpc/test_serializer.py
- src/tests/xmlrpc/test_testbuild.py
- src/tests/xmlrpc/test_testcase.py
- src/tests/xmlrpc/test_testcaseplan.py
- src/tests/xmlrpc/test_testcaserun.py
- src/tests/xmlrpc/test_testplan.py
- src/tests/xmlrpc/test_testrun.py
- src/tests/xmlrpc/test_user.py
> Shorten imports list from tests.factories

- README.rst
This PR fixes grammatical glitches in README.rst
If this is a welcome effort, I could work on fixing grammatical glitches in other documentation files.
I would really love to work on this.
> Fix grammar in README

- src/tcms/testcases/models.py
- src/tcms/testcases/views.py
- src/tests/factories.py
- src/tests/testcases/test_views.py
> Refactor clone cases

- src/tcms/auth/views.py
- src/tcms/comments/views.py
- src/tcms/core/ajax.py
- src/tcms/core/templatetags/ifin.py
- src/tcms/core/templatetags/split_as_option.py
- src/tcms/management/views.py
- src/tcms/report/data.py
- src/tcms/report/forms.py
- src/tcms/testcases/forms.py
- src/tcms/testcases/models.py
- src/tcms/testcases/views.py
- src/tcms/testplans/models.py
- src/tcms/testplans/views.py
- src/tcms/testruns/forms.py
- src/tcms/testruns/helpers/serializer.py
- src/tcms/testruns/models.py
- src/tcms/testruns/views.py
- src/tcms/xmlrpc/api/testrun.py
- src/tcms/xmlrpc/api/user.py
- src/tcms/xmlrpc/serializer.py
- src/tcms/xmlrpc/utils.py
> Remove trailing line breakers

- .travis.yml
> Pull image on-demand in Travis-CI

- src/tcms/testcases/views.py
- src/tcms/testruns/views.py
> Remove another two trailing line breakers

- src/tcms/core/helpers/comments.py
- src/tcms/xmlrpc/api/auth.py
- src/tcms/xmlrpc/api/build.py
- src/tcms/xmlrpc/api/env.py
- src/tcms/xmlrpc/api/product.py
- src/tcms/xmlrpc/api/tag.py
- src/tcms/xmlrpc/api/testcase.py
- src/tcms/xmlrpc/api/testcaseplan.py
- src/tcms/xmlrpc/api/testcaserun.py
- src/tcms/xmlrpc/api/testplan.py
- src/tcms/xmlrpc/api/testrun.py
- src/tcms/xmlrpc/api/user.py
- src/tcms/xmlrpc/api/version.py
Remove '>>> ' from example code lines.
Fixes #460
> Reformat code lines in XMLRPC API examples

- src/tests/testcases/test_views.py
* Assertions on cloned cases do not depend on the order of cases to be
cloned.
* Refactor and add test for cloning cases into same plan.
> Fix tests for case clone

- src/templates/plan/cases_rows.html
> Fix template tag

- src/tcms/testcases/forms.py
- src/tcms/testcases/models.py
- src/tcms/xmlrpc/api/testcase.py
- src/tcms/xmlrpc/filters.py
- src/tests/xmlrpc/test_testcase.py
- src/tests/xmlrpc/utils.py
> Add tests to testcases XMLRPC API

- src/tests/xmlrpc/test_product.py
> Add tests to XMLRPC product APIs

- src/tests/xmlrpc/test_env.py
> Add tests to XMLRPC env APIs

- src/tcms/comments/views.py
- src/tests/test_comments.py
Refactor some lines of code in comments/views.py
Signed-off-by: Chenxiong Qi <cqi@redhat.com>
> Add tests for comments/views.py

- src/tcms/testplans/helpers/email.py
- src/tests/test_linkreference.py
- src/tests/testplans/test_importer.py
- src/tests/testplans/test_models.py
- src/tests/xmlrpc/test_user.py
> Add more tests to several apps

- src/tcms/linkreference/models.py
- src/tcms/linkreference/urls.py
- src/tcms/linkreference/views.py
- src/tcms/testruns/forms.py
- src/tests/__init__.py
- src/tests/test_linkreference.py
- src/tests/testruns/test_views.py
> Add tests to app linkreference

- src/tcms/testcases/views.py
- src/tcms/testruns/views.py
> Fix default_tester in both defer and select_related (#512)

- src/tcms/core/ajax.py
- src/tests/core/test_ajax.py
> Fix get error message when default tester does not exist

- src/static/js/testplan_actions.js
> Fix wrong parameter passed to backend while typing tag name

- README.rst
> Add PyPI badge to README

- src/static/js/advance_search.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> Use triple equals in JS code

- src/static/js/createrun.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/report.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> Js code quality

- setup.py
- src/tests/core/test_commands.py
- src/tests/core/test_core.py
- src/tests/core/test_files.py
- src/tests/issuetracker/test_services.py
- src/tests/issuetracker/test_task.py
- src/tests/test_auth.py
- src/tests/testcases/test_models.py
- src/tests/testcases/test_views.py
- src/tests/testplans/test_forms.py
- src/tests/testplans/test_models.py
- src/tests/testruns/test_views.py
- src/tests/xmlrpc/test_testcase.py
- src/tests/xmlrpc/test_user.py
> Remove dependency of mock

- src/tcms/comments/urls.py
- src/tcms/core/urls.py
- src/tcms/linkreference/urls.py
- src/tcms/management/urls.py
- src/tcms/profiles/urls.py
- src/tcms/report/urls.py
- src/tcms/search/urls.py
- src/tcms/testcases/urls/case_urls.py
- src/tcms/testcases/urls/cases_urls.py
- src/tcms/testplans/urls/plan_urls.py
- src/tcms/testplans/urls/plans_urls.py
- src/tcms/testruns/urls/run_urls.py
- src/tcms/testruns/urls/runs_urls.py
- src/tcms/urls.py
> Replace url with path in URLconf

- src/static/js/testplan_actions.js
> JS: fix wrong variable name in plan treeview

- src/static/js/testcase_actions.js
> JS: remove unused function

- src/templates/case/attachment.html
- src/templates/case/edit.html
- src/templates/case/printable.html
- src/templates/plan/attachment.html
- src/templates/plan/edit.html
- src/templates/plan/report.html
> Remove unused CSS from templates

- src/templates/plan/get_review_cases.html
> Add missing load tag to load static

- src/static/js/advance_search.js
- src/static/js/deleconfirm.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/report.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
These changes include following major refactors:
* Reduce unnecessary variables.
* Move some callback functions into the parameter properly.
> JS: massive refactors

- src/static/js/deleconfirm.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
By using argument dataType, lots of code could be saved to parse JSON
data returned from server side.
> JS: use jquery ajax dataType argument

- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
Another fixes to unnecessary variable usage and unnecessary separate
callback function definition.
> JS: more small fixes

- src/tcms/profiles/forms.py
> Use apps.get_model in bookmark

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: fix typo serialzeCaseForm

- src/static/js/testplan_actions.js
> JS: fix typo initializaRunTab

- src/static/js/tcms_actions.js
> JS: remove unused removeBatchTag

- src/static/js/testplan_actions.js
> JS: massive refactor TreeView

- src/static/js/createrun.js
- src/static/js/index.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/report.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: replace live and bind with on

- src/templates/tcms_base.html
> JS: use let to declare global variable jQ

- src/templates/tcms_base.html
> JS: fix location to load django admin jquery

- src/static/js/testrun_actions.js
- src/templates/run/clone.html
* Selected case runs are not shown in test run clone page.
* django jQuery lib is not loaded properly.
> Fix test run clone page

- src/static/js/testrun_actions.js
> JS: rewrite serializeCaseRunFromInputList

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/tests/js/js-tests.html
- src/tests/js/test-tcms-actions.js
> JS: write more tests for functions

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
> JS: remove duplicate serializeCaseForm and serializeCaseForm2

- src/tests/js/js-tests.html
- src/tests/js/test-tcms-actions.js
- src/tests/js/test-testcase-actions.js
Move tests to separate test files dedicated for each JavaScript modules,
e.g. tcms_actions.js and testcase_actions.js.
> JS: relayout tests

- src/static/js/testplan_actions.js
> JS: remove unused code

- src/static/js/deleconfirm.js
- src/tcms/core/files.py
- src/tcms/core/urls.py
- src/tests/core/test_files.py
> Set HTTP response status code properly for removing attachment

- .travis.yml
- setup.py
> Remove Django 2.0

- src/static/js/management_actions.js
- src/tcms/core/responses.py
- src/tcms/management/models.py
- src/tcms/management/urls.py
- src/tcms/management/views.py
- src/templates/environment/ajax/property_values.html
- src/templates/environment/group_edit.html
- src/templates/environment/groups.html
- src/templates/environment/property.html
- src/tests/test_management.py
The original intention is to response AJAX request with proper HTTP
status code. However, as a result, every view is refactored totally and
the URL scheme is refined.
> Massive refactor management environment views

- src/static/js/testrun_actions.js
- src/tcms/linkreference/views.py
- src/tests/test_linkreference.py
> Refine linkreference AJAX response

- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
- src/tcms/testplans/views.py
- src/tests/testplans/test_views.py
> Refine testplans AJAX response

- src/tcms/comments/exceptions.py
- src/tcms/comments/models.py
- src/tcms/comments/views.py
- src/tcms/core/files.py
- src/tcms/core/mailto.py
- src/tcms/core/utils.py
- src/tcms/testplans/importer.py
- src/tests/core/test_core.py
- src/tests/core/test_files.py
- src/tests/core/test_views.py
- src/tests/factories.py
- src/tests/issuetracker/test_models.py
- src/tests/test_comments.py
- src/tests/testplans/test_importer.py
- src/tests/testplans/test_signals.py
- src/tests/xmlrpc/test_product.py
- src/tests/xmlrpc/test_testcase.py
> Add more tests

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/tcms/issuetracker/models.py
- src/tcms/testcases/forms.py
- src/tcms/testcases/views.py
- src/tests/testcases/test_views.py
> Use HTTP status code properly in testcases

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tcms/core/ajax.py
- src/tests/core/test_ajax.py
- src/tests/core/test_views.py
> Cleanup core/ajax.py for the JSON response

- src/tcms/testruns/ajax.py
- src/tests/testruns/test_views.py
> Refine HTTP response in app testruns

- src/static/js/profiles.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tcms/comments/views.py
- src/tcms/linkreference/views.py
- src/tcms/profiles/views.py
- src/tcms/testcases/actions.py
- src/tcms/testruns/views.py
- src/tests/test_comments.py
- src/tests/test_linkreference.py
- src/tests/testcases/test_views.py
- src/tests/testruns/test_views.py
> Refine more HTTP response status code and fix js

- src/static/js/testcase_actions.js
- src/tcms/testcases/forms.py
- src/tcms/testcases/urls/case_urls.py
- src/tcms/testcases/views.py
- src/templates/case/get.html
- src/templates/case/get_plan.html
- src/templates/plan/preview.html
- src/tests/testcases/test_views.py
This refactor is for the plans tab in a case page. Both frontend and
backend code are refactored.
> Massive refactor of adding case to plans

- src/static/js/testplan_actions.js
- src/templates/plan/get_component.html
> Update components button works again

- src/static/js/advance_search.js
- src/static/js/createrun.js
- src/static/js/footer_at_the_end.js
- src/static/js/index.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: use let or const instead of var

- README.rst
> Talk on Gitter

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
> JS: clean some code

- src/tcms/core/ajax.py
- src/tests/core/test_views.py
> Comment out all selected case runs correctly

- src/tcms/logs/views.py
- src/tests/core/test_core.py
> Fix log_action to handle None original value correctly

- setup.py
> Remove Django 2.0 from project classifiers

- src/tcms/core/files.py
- src/templates/case/attachment.html
- src/templates/plan/attachment.html
> Add missing csrf check for attachment upload

- src/static/js/advance_search.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: simplify handling default value

- src/templates/plan/edit.html
> Fix wrong static tag in plan/edit template

- MANIFEST.in
> Add missing src/manage.py

- docs/source/releases/index.rst
> Add release notes of 4.6.1 to TOC

- .travis.yml
- README.rst
- setup.py
- src/tcms/issuetracker/models.py
- src/tests/testcases/test_models.py
- src/tests/testcases/test_views.py
- tox.ini
In order to work with Django 3.0, a few dependencies are upgraded.
Closes #631
> Work with Django 3.0 - #631

- .eslintrc.js
- .gitignore
- .travis.yml
- src/static/js/createrun.js
- src/static/js/deleconfirm.js
- src/static/js/index.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/templates/plan/choose_testrun.html
- src/templates/run/clone.html
- src/templates/run/get.html
- src/tests/js/js-tests.html
- src/tests/js/test-testplan-actions.js
- tox.ini
eslint is added to lint JavaScript code. The config is started with
minimum necessary configs. The rules is empty for this initiative. More
rules will be added later and code style issues will be fixed
accordingly.
Fixes #573
> JS: lint JavaScript code

- .travis.yml
- contrib/travis-ci/Dockerfile
Adding this is because the Quay.io is down and PR verification is
blocked.
> Reliable testbox

- .travis.yml
- contrib/travis-ci/Dockerfile
- contrib/travis-ci/entrypoint.sh
> Wait for mysql container to launch

- README.rst
- contrib/travis-ci/testrunner.py
- docs/source/index.rst
> Upgrade test database images

- contrib/travis-ci/Dockerfile
> Upgrade testbox base image to fedora:32

- setup.py
- src/tcms/settings/common.py
> Upgrade django-tinymce to 3.0.2

- .travis.yml
Only run tests with non-SQLite database engines and Python 3.7.
> Exclude some jobs from Travis-CI

- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> Replace fireEvent with jQuery trigger

- .eslintrc.js
- src/static/js/advance_search.js
- src/static/js/createrun.js
- src/static/js/deleconfirm.js
- src/static/js/footer_at_the_end.js
- src/static/js/index.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/report.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tests/js/test-tcms-actions.js
> JS: lint js code with more rules

- src/templates/plan/search_case.html
> Add missing csrf_token

- src/templates/case/common/case_advance_filtered.html
- src/templates/case/common/case_filtered.html
> Add missing csrf_token to templates

- src/tcms/logs/views.py
> Replace smart_text with smart_str

- src/static/js/testplan_actions.js
- tox.ini
> JS: expand addBatchTag to the function where it is called

- src/static/js/comment.js
- src/static/js/tcms_actions.js
- src/templates/plan/get.html
- src/templates/run/get.html
> JS: move comment functions to a separate js file

- src/static/js/tcms_actions.js
> JS: remove argument parameters

- src/static/js/report.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tcms/testruns/forms.py
> JS: cleanup product associated objects updater functions

- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: use one line to set disabled property

- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
> JS: merge toggleTestCasePane and toggleTestCaseReviewPane

- src/templates/management/get_tag.html
- src/templates/tcms_base.html
> JS: use jQuery on to listen events in templates

- src/static/js/testrun_actions.js
- src/templates/run/assign_case.html
> JS: replace toggleAllCheckBoxes with shiftcheckbox

- src/templates/run/assign_case.html
> Add missing csrf_token in assgin_case template

- .eslintrc.js
- src/static/js/comment.js
- src/static/js/testrun_actions.js
- src/templates/run/table_caseruns.html
> JS: fix comments submittion and removal

- .eslintrc.js
- src/static/js/tcms_actions.js
- src/static/js/testrun_actions.js
- src/templates/run/get_environment.html
> JS: replace add property template with jQuery dialog

- src/templates/plan/get_cases.html
- src/templates/plan/get_review_cases.html
- src/templates/plan/report.html
- src/templates/prompt.html
- src/templates/run/get_case_runs.html
> Remove commented out lines of templates

- src/tcms/core/files.py
> Refactor files.py to reduce indentations

- src/tcms/core/files.py
- src/tcms/management/models.py
- src/tests/core/test_files.py
- src/tests/factories.py
> Enhance attachements

- src/templates/run/get_case_runs.html
> Set  javascript:void(0) in dropdown menu items in test run page

- src/static/js/testrun_actions.js
- src/tests/js/js-tests.html
- src/tests/js/test-testrun-actions.js
> JS: getSelectCaseRunIDs returns an array now

- src/static/js/tcms_actions.js
> JS: fix objectPk type description

- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tests/js/js-tests.html
- src/tests/js/test-tcms-actions.js
- src/tests/js/test-testrun-actions.js
Make it flexible for calling with alternative URL easily.
An important thing is, this is the first commit introducing
jquery-mockjax to mock jQ.ajax.
> JS: refactor updateObject

- src/static/js/testplan_actions.js
> JS: simplify constructPlanDetailsCasesZoneCallback

- src/static/js/testplan_actions.js
> JS: remove duplicates from testplan_actions.js

- src/templates/plan/get_cases.html
- src/templates/plan/get_review_cases.html
> Replace #testcases with javascript:void(0) in plan page

- src/tcms/core/context_processors.py
- src/tcms/settings/common.py
- src/templates/case/edit.html
- src/templates/case/new.html
- src/templates/menu.html
- src/templates/plan/new.html
- src/templates/run/clone.html
- src/templates/run/edit.html
- src/templates/run/new.html
> Reverse admin urls

- src/static/js/testrun_actions.js
- src/tcms/testruns/forms.py
- src/tcms/testruns/urls/runs_urls.py
- src/tcms/testruns/views.py
- src/tests/testruns/test_views.py
> Refactor view env_value to class-based views

- src/static/js/testcase_actions.js
- src/tcms/core/forms/fields.py
- src/tcms/report/forms.py
- src/tcms/testcases/forms.py
- src/tcms/testcases/urls/case_urls.py
- src/tcms/testcases/views.py
- src/templates/case/get_issues.html
- src/tests/testcases/test_views.py
> Refactor manage_case_issues into class-based views (#578)

- src/templates/case/comments_of_reviewing_cases.html
- src/templates/case/get_details_case_run.html
- src/templates/case/history.html
- src/templates/comments/comments.html
- src/templates/menu.html
- src/templates/plan/cases_table.html
- src/templates/plan/clone.html
- src/templates/plan/get.html
- src/templates/plan/history.html
- src/templates/profile/bookmarks.html
- src/templates/profile/info.html
- src/templates/profile/recent.html
- src/templates/report/caseruns_table.html
- src/templates/report/custom_details_status_matrix.html
- src/templates/report/nav.html
- src/templates/report/testing-report/per_build_report.html
- src/templates/report/testing-report/per_plan_build.html
- src/templates/report/testing-report/per_plan_tag.html
- src/templates/report/testing-report/per_priority_report.html
- src/templates/run/clone.html
- src/templates/run/edit.html
- src/templates/run/get.html
- src/templates/run/get_case_runs.html
- src/templates/run/status_statistics.html
- src/templates/run/table_caseruns.html
- src/templates/search/results.html
- src/templates/xmlrpc.html
> Replace ifequal and ifnotequal with if (#716)

- src/tcms/core/utils.py
- src/tcms/testcases/views.py
- src/tcms/testruns/ajax.py
- src/tcms/testruns/views.py
- src/tcms/xmlrpc/api/testcase.py
- src/tcms/xmlrpc/api/testcaserun.py
> Fix typo form_error_messags_to_list

- src/templates/case/clone.html
- src/templates/case/common/case_advance_filtered.html
- src/templates/case/get_details_case_run.html
- src/templates/plan/cases_table.html
- src/templates/plan/form/search_case.html
- src/templates/plan/get.html
- src/templates/run/assign_case.html
- src/templates/run/clone.html
- src/templates/run/form/search_case.html
- src/templates/run/get.html
- src/templates/run/get_case_runs.html
- src/templates/run/get_environment.html
- src/tests/testcases/test_views.py
- src/tests/testruns/test_views.py
> Fix HTML attrs disabled, selected and checked

- src/tcms/core/utils.py
- src/tcms/testruns/views.py
> Fix wrong variable type passed to DataTableResult

- .travis.yml
- contrib/travis-ci/Dockerfile
- contrib/travis-ci/testrunner.py
- setup.py
- tox.ini
> Add Python 3.8 to testenv (#725)

- src/static/js/testplan_actions.js
> Fix wrong buttons CSS class in plans search result page

- README.rst
> Remove downloads badge

- src/tcms/search/urls.py
- src/templates/case/all.html
- src/templates/menu.html
- src/templates/plan/all.html
- src/templates/run/all.html
- src/templates/search/advanced_search.html
- src/templates/search/results.html
- src/tests/test_search.py
> Do not hardcode advanced search url in templates

- src/tcms/search/forms.py
> Add types to search/forms.py

- src/tests/xmlrpc/test_testplan.py
> Add tests for XMLRPC API TestPlan.create

- .eslintrc.js
- .travis.yml
- src/static/js/comment.js
- src/static/js/management_actions.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: lint jsdoc (#677)

- .travis.yml
- Makefile
- contrib/travis-ci/build-rpm.sh
> New CI job: test building rpm package

- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
> JS: reuse datatable common settings (#755)

- src/templates/run/clone_multiple.html
> Add missing csrf_token for multiple runs clone (#765)

- src/static/js/testrun_actions.js
- src/tcms/core/db.py
- src/tcms/testruns/data.py
- src/tcms/testruns/views.py
- src/templates/run/get_case_runs.html
- src/templates/run/status_statistics.html
- src/tests/core/test_core.py
- src/tests/testruns/test_data.py
> Refactor stats caseruns status

- src/tcms/profiles/views.py
- src/tcms/testruns/models.py
- src/templates/profile/recent.html
- src/tests/test_profile.py
> Reduce SQL queries count in recent page (#754)

- src/tcms/xmlrpc/api/auth.py
- src/tests/xmlrpc/test_auth.py
> Pass missing request argument to backend.authentication (#498)

- src/static/js/management_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: use this properly to shorten lines

- src/static/style/base.css
> Fix 'px' is redundant for value 0px

- src/static/js/testplan_actions.js
> JS: fix cases tab can't reload after case status is changed

- src/templates/registration/registration_form.html
> Add missing csrf_token to user registration form (#792)

- src/tcms/management/migrations/0008_add_checksum_to_testattachment.py
- src/tcms/management/models.py
> Use apps.get_model to get TestAttachment model

- .github/workflows/unittests.yaml
> Fix coveralls step name and wrong env var name

- MANIFEST.in
> Add docker/ to sdist

- .github/workflows/unittests.yaml
- README.rst
- setup.py
- src/tcms/xmlrpc/filters.py
- src/tcms/xmlrpc/utils.py
- tox.ini
> Add Django 3.1 to testenv (#800)

- .github/workflows/package-build.yaml
> Test f33 package build (#804)

- README.rst
- tox.ini
> Upgrade database engine in testenv (#805)

- .github/workflows/unittests.yaml
- README.rst
> Replace CI badge with GitHub workflow status

- README.rst
> Adjust badges rendering for GitHub

- .github/workflows/unittests.yaml
- README.rst
- setup.py
- tox.ini
> Add py39 to testenv (#806)

- docker/released/Dockerfile
> Fix python version in the site-packages path

- .github/workflows/distribution.yaml
This release workflow works on the GitHub actions, there are three steps one by
one:
* Build source distribution package and publish to PyPI
* Build RPM package in Copr, which requires the source distribution package
* Build release image, which installed nitrate-tcms from the YUM repository
* generated in Copr
For more details, please refer to the distribution.yaml
> Add release workflow

- Makefile
> Housekeeping on Makefile

- docker-compose-dev.yml
- docker-compose.yml
> Unify mariadb version in docker-compose config file

- .github/workflows/unittests.yaml
- src/static/style/base.css
This reverts commit e1796d31b1c68c0104b3a3766ba6fb732183410c.
> Revert "Fix 'px' is redundant for value 0px"

- src/static/js/tcms_actions.js
- src/tests/js/test-tcms-actions.js
> JS: rewrite constructAjaxLoading using DOM API

- src/static/js/management_actions.js
> JS: fix wrong use of this keyword management_actions

- .github/workflows/distribution.yaml
- .github/workflows/package-build.yaml
- src/tcms/search/views.py
> Reduce lots of SQL queries in advanced search

- setup.py
> Add tox and tox-docker extra deps list

- src/static/js/testplan_actions.js
> JS: fix wrong plan advanced search pagination info

- src/static/js/testrun_actions.js
- src/templates/case/get_details_case_run.html
> JS: use meaningful data attribute names in case run detail pane

- src/static/js/testrun_actions.js
> Do not expand next if the last case run is updated

- src/static/js/testrun_actions.js
- src/tcms/testruns/urls/run_urls.py
- src/tcms/testruns/views.py
- src/templates/run/get.html
- src/templates/run/status_statistics.html
> Refresh run statistics after changing case run status

- src/templates/plan/edit.html
> Fix template plan/edit.html

- src/static/style/base.css
- src/tcms/testcases/data.py
- src/templates/case/get_details_case_case_run.html
- src/templates/case/get_details_case_run.html
- src/templates/case/get_log.html
- src/tests/testcases/test_views.py
> Case run change logs are shown correctly under Case Runs tab

- src/tcms/testruns/views.py
- src/tcms/urls.py
> Remove unused code from testruns app

- src/tcms/testcases/data.py
- src/tcms/testcases/models.py
- src/tcms/testcases/views.py
> Remove duplicate SQL queries during loading case run detail pane

- src/templates/tcms_base.html
> Declare HTML5 in base template

- .github/workflows/linter.yaml
- .github/workflows/package-build.yaml
- .github/workflows/unittests.yaml
- src/templates/plan/get.html
- src/templates/plan/get_cases.html
> Fix the unusable add tag dialog under reviewing cases tab

- src/tcms/testruns/views.py
- src/tests/testruns/test_views.py
> Fix incorrect test run issues count when refresh the statistics

- src/static/js/testplan_actions.js
- src/templates/plan/action_controls_on_cases.html
- src/templates/plan/cases_table.html
- src/templates/plan/edit.html
- src/templates/plan/get.html
- src/templates/plan/get_runs.html
- src/templates/plan/get_treeview.html
- src/templates/plan/search_result.html
> JS: use dataset in test plan features

- src/static/js/management_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testrun_actions.js
- src/tcms/xmlrpc/serializer.py
- src/templates/case/history.html
- src/templates/case/new.html
- src/templates/environment/ajax/property_values.html
- src/templates/environment/property.html
- src/templates/run/common/run_filtered.html
- src/templates/run/search_result.html
- src/tests/xmlrpc/test_testplan.py
> JS: use dataset in case, plan, run, environment features

- src/tcms/core/utils.py
- src/tcms/testcases/views.py
- src/tcms/testruns/data.py
- src/tcms/testruns/helpers/serializer.py
- src/tcms/xmlrpc/utils.py
> Fix docstrings using sphnix Python domain syntax

- src/static/js/management_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/templates/case/get_issues.html
- src/templates/environment/groups.html
- src/templates/plan/action_controls_on_cases.html
- src/templates/run/get_environment.html
- src/templates/run/new.html
> JS: use dataset to replace data-params

- src/tcms/testruns/helpers/serializer.py
- src/templates/run/export-to.xml
- src/tests/testruns/test_serializer.py
- src/tests/testruns/test_views.py
> Fix incorrect log link url encode

- src/tcms/settings/common.py
- src/tcms/settings/product.py
> Cleanup settings

- contrib/conf/nitrate-httpd.conf
> Fix wrong Python version in WSGIScriptAlias path (#872)

- README.rst
> Add Fedora Copr badge

- docker-compose-dev.yml
- docker-compose.yml
- python-nitrate-tcms.spec
- src/tcms/settings/common.py
- src/tcms/settings/devel.py
- src/tcms/settings/product.py
- src/tcms/settings/test.py
- tox.ini
Please refer to Django's settings documentation to learn background.
> SECRET_KEY must be set explicitly

- docker/released/Dockerfile
- docker/released/README.md
- docker/released/entrypoint.sh
- docker/released/init.py
> Add entrypoint to release image (#459)

- .github/workflows/package-build.yaml
> Test building Fedora rawhide package

- .github/workflows/unittests.yaml
- README.rst
- setup.py
- tox.ini
> Drop Django 2.1 (#884)

- setup.py
> Upgrade celery to 5.0.5

- docker/Dockerfile
> Quote empty value for vendor label properly

- docker/Dockerfile
> Reduce image size

- .github/workflows/dev-release.yaml
- .github/workflows/package-build.yaml
> Prevent Fedora rawhide from impacting CI

- Makefile
- python-nitrate-tcms.spec
- setup.py
- tox.ini
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_python_extras
> Refactor SPEC file to build subpackages for extras

- python-nitrate-tcms.spec
- setup.py
- src/tcms/issuetracker/task.py
- tox.ini
> Make python-bugzilla optional

- src/tcms/settings/common.py
- src/tcms/testcases/helpers/email.py
- src/tcms/testplans/helpers/email.py
> Reference some mail templates directly

- docker/Dockerfile
> Upgrade base image to f33

- docker/README.md
> Update image README

- docs/source/contribution.rst
- docs/source/set_dev_env.rst
The two documents are updated to make it up-to-date.
> Update contribution docs

- .github/workflows/dev-release.yaml
- .github/workflows/distribution.yaml
- .github/workflows/package-build.yaml
- Makefile
- python-nitrate-tcms.spec
> Build f34 RPM (#909)

- .github/workflows/unittests.yaml
- tox.ini
> Run tests in py3.9 with various database engines (#912)

- README.rst
- docs/source/install/index.rst
> Update docs about getting Nitrate

- contrib/scripts/release-notes.tmpl.rst
> Update release notes template (#923)

- MANIFEST.in
> Exclude .mypy_cache/ from sdist (#927)

- .github/workflows/unittests.yaml
> Fix package name libcrypt-dev

- contrib/scripts/adjust_mysql_auth_plugin.sh
- src/tcms/core/apps.py
- tox.ini
> Fix py39 testenv

- contrib/conf/nitrate-httpd.conf
> Fix python version for the WSGI conf (#931)

- setup.cfg
> Remove seldom used devtools packages

- .github/workflows/unittests.yaml
- contrib/scripts/adjust_mysql_auth_plugin.sh
- setup.cfg
- src/tcms/settings/test.py
- tox.ini
> Upgrade tox-docker>=2.0.0 (#916)

- src/tcms/core/views/error.py
> Fix wrong Template.render call in 500 error handler

- src/tcms/settings/devel.py
> Remove django_extensions from devel apps list

- src/static/js/testrun_actions.js
- src/tcms/core/ajax.py
- src/tcms/testruns/forms.py
- src/tcms/testruns/urls/runs_urls.py
- src/tcms/testruns/views.py
- src/tcms/urls.py
- src/tests/core/test_views.py
- src/tests/testruns/test_views.py
> Move comment_case_runs view to testruns app (#913)

- src/tcms/core/ajax.py
> Refactor objects info view to make it more readable (#913)

- container/Containerfile
> Fix httpd conf path in Containerfile

- container-compose.yml
The web container port has been changed to 8080.
> Fix the container port in the compose

- .eslintrc.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/templates/management/get_tag.html
> JS: rewrite tags management

- .github/workflows/linter.yaml
- .github/workflows/unittests.yaml
- README.rst
- setup.cfg
- tox.ini
> py39 is the minimum required version (#984)

- .github/workflows/linter.yaml
- .github/workflows/package-build.yaml
- .github/workflows/unittests.yaml
> The main branch has moved to main branch (#921)

- .readthedocs.yml
> Use Python 3.9 to build docs in RTD (#1020)

- .readthedocs.yml
> Use rtd v2 config format (#1024)

- .readthedocs.yml
> Install missing deps for rtd build

- docs/source/releases/index.rst
> Add missing release notes to the toc

- .readthedocs.yml
> Fix conf.py path in rtd config

- .eslintrc.js
- src/static/js/tcms_actions.js
- src/tests/js/test-tcms-actions.js
> JS: constructForm does not rely on jquery (#1022)

- src/static/js/testrun_actions.js
- src/tcms/testplans/views.py
- src/templates/plan/choose_testrun.html
- src/tests/testplans/test_views.py
Also rewrite the form submission. It does not rely on JavaScript code
anymore.
closes #1037
> Add missing csrf token for choosing cases to runs (#1037)

- src/static/js/testrun_actions.js
> JS: avoid showing NaN when change None sort key (#1013)

- src/tcms/testplans/urls/plan_urls.py
- src/tcms/testplans/views.py
- src/tests/testplans/test_views.py
> Remove testplans.views.delete (#968)

- src/static/js/tcms_actions.js
> Use Array.isArray in Nitrate.Utils.formSerialize (#1017)

- src/static/js/nitrate.toggledetail.js
- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tests/js/test-tcms-actions.js
> Call document.createElement to create DOM elements (#1038)

- src/static/js/nitrate.toggledetail.js
> Rewrite DetailExpansion in class (#972)

- .github/workflows/dev-release.yaml
- .github/workflows/distribution.yaml
- .github/workflows/linter.yaml
- .github/workflows/package-build.yaml
- container/Containerfile
- container/Containerfile-worker
> Drop f33 and use f35 in ci

- setup.cfg
> Upgrade extras dependencies

- README.rst
> Update irc info in README

- src/tcms/testcases/views.py
- src/tcms/testplans/views.py
- src/tcms/xmlrpc/decorators.py
- tox.ini
> Upgrade black version

- contrib/conf/nitrate-httpd.conf
> Fix wsgi script path in httpd conf (#1065)

- src/static/js/comment.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
> JS: remove submitComment (#1047)

- src/static/js/testplan_actions.js
> JS: remove unused argument (#1049)

- setup.cfg
> Add django-stubs to devtools as extra_require

- .github/workflows/unittests.yaml
- README.rst
- setup.cfg
- tox.ini
> Remove Django 2.2 from testenv (#1072)

- setup.cfg
> Update Django requirement in setup.cfg

- src/tcms/core/ajax.py
- src/tcms/management/models.py
- src/tcms/testcases/models.py
> Rename the last model list method to search

- src/tcms/management/models.py
- src/tcms/testcases/models.py
- src/tcms/testplans/models.py
- src/tests/conftest.py
- src/tests/test_management.py
> Use walrus operator to simplify some code

- .github/workflows/dev-release.yaml
> Remove f34 from dev-release CI task

- setup.cfg
> Upgrade celery version

- README.rst
> Remove gitter info from readme

- src/tcms/report/views.py
> Fix KeyError for generating testing report (#1094)

- .github/workflows/linter.yaml
- .github/workflows/unittests.yaml
> Remove branch pattern release-*.* from CI (#1105)

- .github/workflows/distribution.yaml
> Fix wrong repo name format passed to actions/checkout (#1109)

- .github/workflows/dev-release.yaml
> Fix wrong repo name format

- setup.cfg
> Pin requirements (#1052)

- MANIFEST.in
> Cleanup MANIFEST.in
