Nitrate/Nitrate

- tcms/templates/run/status_statistics.html
- tcms/templates/run/table_caseruns.html
Also fix comments_count by casting the primary key value to string because the dict structure containing the values uses string keys, not integers.
NOTE: There are quire a few static images assigned dynamically from the JavaScript files or from CSS styles. I can make these work by treating JS and CSS as templates and using the ``STATIC_URL variable``. This is dependent on django-compressor, which in turn needs a recent Django version (see my other PR).
> Use STATIC_URL for a few images

- tcms/xmlrpc/__init__.py
I have updated the fix for the traceback introduced in PR #86 . Also removed the noqa keyword so that flake8 will actually report the error here. Seems to work for me.
> Fix traceback introduced by PR #86

- requirements/base.txt
- setup.cfg
- tcms/core/utils/__init__.py
- tcms/static/js/testplan_actions.js
- tcms/static/js/testrun_actions.js
- tcms/templates/plan/common/json_plan_runs.txt
- tcms/templates/plan/get_runs.html
- tcms/templates/run/all.html
- tcms/templates/run/common/json_runs.txt
- tcms/templates/search/runs.html
- tcms/testplans/urls/plan_urls.py
- tcms/testplans/views.py
- tcms/testruns/forms.py
- tcms/testruns/models.py
- tcms/testruns/urls/run_urls.py
- tcms/testruns/views.py
Two places to show test runs within DataTable, they are Search Runs and
Runs tab in a plan page.
* Unused code is cleaned (removed).
* Using DataTable to show test runs. Runs are paginated and to get each
page of runs by an AJAX request.
* Refactored TestRun.list by a table-driven method. Lots of lines of
code are saved.
* python-six is now a dependency
* reformat template files
> using DataTable to show test runs

- tcms/testplans/views.py
Normal Search is fixed in "Add cases from other plans", now it can
search cases normally. Also, remove unnecessary fields from query list.
> Fix Normal Search

- requirements/base.txt
This patch make it possible to install kobo including the required
kobo-django from source directly.
> Install kobo from source

- CHANGELOG.rst
- docs/source/guide/testcase.rst
- tcms/testcases/forms.py
- tcms/testplans/views.py
@tkdchen I have updated the help strings for test plan clone form which fixes #67 IMO. Let me know if you approve the text so I can create new screenshot images. 
Note: while testing this I found a regression. You have removed some code in d4f815f which breaks plan filtering. I have added it back. There are 3 if statements, the first one is used when filtering plans during test case cloning. The other 2 I have no idea what they do and if they are needed. 
Can you explain when these if statements are used and why you have deleted them previously ?
> Fix regression & update help strings when clonning

- Makefile
- requirements/devel.txt
- setup.cfg
- tcms/settings/test.py
This patch replaces nose with pytest as the test runner to run tests due
to several major reasons.
- nose is currently in maintenance mode and will not have new features
in the future, whereas pytest has active development in contrast.
- Nitrate is a little special with its core class names, e.g. TestCase,
TestPlan, TestRun, all these names could confuse nose easily to treat
them as a test rather than a normal feature class. The runner only
requires to collect classes derived from either django.test.TestCase
or unittest.TestCase. pytest makes this easier to implement with less
and easy-to-understand configuration.
- As a result of using pytest, runnng test is simplified. Just
`py.test'. There is no default test runner for integrating with
django's test command, but it's easy to write one …
> Replace nose with pytest to run tests

- CHANGELOG.rst
- docs/source/configuration.rst
- docs/source/index.rst
- docs/source/installing_gce.rst
- docs/source/installing_gunicorn.rst
- docs/source/installing_in_rhel.rst
- docs/source/installing_in_virtualenv.rst
- docs/source/upgrading.rst
@tkdchen 
- updated for RHEL 7
- the preferred way to install is using virtualenv
- simplified WSGI config but kept reference to previous example
- split Upgrading and Configuration in separate sections b/c I
intend to write more info for that
Note: the biggest change is installing with virtualenv and not directly into the system path. I believe virtualenv is the preferred way to host Django (and Python) applications. At least sites like DigitalOcean recommend it. It provides benefits and doesn't really add a lot of overhead when creating the environment so IMO this is an acceptable change.
> Update Installing in RHEL docs

- .travis.yml
after a successfull build Travis-CI will send coverage information to coveralls.io. 
@tkdchen if you enable Coveralls for the Nitrate/Nitrate repo it will start working automatically. Also we can then add a nice badge to the README showing how much coverage we've got. Coveralls also records the history so you can traverse how coverage did change over time. Here's an example from another project I am working on: https://coveralls.io/github/chartit/django-chartit
> Enable Coveralls.io

- .coveragerc
- tcms/testcases/tests.py
- tcms/testplans/tests.py
- tcms/testruns/tests.py
- tcms/tests/__init__.py
- tcms/xmlrpc/tests/test_product.py
- tcms/xmlrpc/tests/test_serializer.py
- tcms/xmlrpc/tests/test_tag.py
- tcms/xmlrpc/tests/test_testbuild.py
- tcms/xmlrpc/tests/test_testcase.py
- tcms/xmlrpc/tests/test_testcaseplan.py
- tcms/xmlrpc/tests/test_testcaserun.py
- tcms/xmlrpc/tests/test_testplan.py
- tcms/xmlrpc/tests/test_user.py
- tcms/xmlrpc/tests/test_utils.py
This is a fix for #161 which removes `tearDownClass` and replaces `setUpClass` with `setUpTestData` which appears to be the recommended Django way since 1.8. It also magically fixes the core dumps in Travis CI. 
The second commit instructs coverage report to omit test files in the report and reveals we have 40% actual code coverage :(
> Update tests and fix Travis CI core dump

- tcms/testcases/models.py
- tcms/testplans/models.py
- tcms/testplans/tests.py
- tcms/xmlrpc/api/testcase.py
- tcms/xmlrpc/tests/test_testcase.py
plus two minor improvements which are also related!
> Add tests, SQL refactor and fixes for commit_unless_managed

- tcms/core/migrations/0001_django_comments__object_pk.py
- tcms/core/migrations/0002_add_initial_data.py
this migration is modifying a 3rd party model and was overriding
app_label to django_comments in order to gain access to the model!
However due to how Django records executed migrations it was
recorded as django_comments|0001... instead of core|0001...! Thus
the migration was seen as still pending and could lead to problems
when applying further migrations.
@tkdchen please review. I think we've got the migration right this time.
> Remove tcms.core.migrations.0001_django_comments__object_pk

- docs/source/installing_in_rhel.rst
since the migration to Django 1.8 we no longer use `syncdb` and `loaddata`.
> Update installation steps for RHEL6

- tcms/testcases/forms.py
- tcms/testcases/models.py
- tcms/testcases/sqls.py
- tcms/testcases/tests.py
- tcms/testcases/views.py
This is a minor refactoring covered by existing tests.
The second commit fixes #174. I will see if I can add automated tests for it as well but please review.
> Refactor SQL in testcases and fix #174

- requirements/base.txt
Version of django-contrib-comments and django-preserialize are
specified explicitly. Both of these two versions are required to
upgrade to Django >=1.9.
Fix #219
> Specify versions for dependent packages

- requirements/base.txt
> Upgrade kerberos to 1.2.5

- tcms/core/utils/__init__.py
- tcms/templates/plan/common/json_plan_runs.txt
- tcms/templates/run/common/json_runs.txt
- tcms/testcases/tests.py
- tcms/testcases/views.py
- tcms/testplans/tests.py
- tcms/testplans/views.py
- tcms/testruns/tests/test_views.py
- tcms/testruns/views.py
New DataTableResult is introduced to handle search objects pagination
and sorting for generating response data for rendering in DataTable in
user's web browser.
Search plans, cases, runs and runs in plan page are modified to use this
new class.
> Refactor datatable response

- tcms/fixtures/cases-to-import.xml
- tcms/static/js/testplan_actions.js
- tcms/templates/plan/get.html
- tcms/templates/plan/get_cases.html
- tcms/templates/plan/search_case.html
- tcms/testplans/forms.py
- tcms/testplans/tests.py
- tcms/testplans/urls/plan_urls.py
- tcms/testplans/views.py
CaseActions is moved and separated to individual view classes for each
operation request. Original cases view method is not used anymore and
removed.
Fix #196
> Refactor inner action class CaseActions

- tcms/static/js/testcase_actions.js
- tcms/static/js/testplan_actions.js
- tcms/templates/case/get_component.html
- tcms/templates/plan/get_component.html
- tcms/testcases/actions.py
- tcms/testcases/tests.py
- tcms/testcases/urls/cases_urls.py
- tcms/testcases/views.py
- tcms/testplans/urls/plans_urls.py
- tcms/testplans/views.py
Both plan and case components have similar actions, add, remove, update
and get components UI. But, they have different behavior to accomplish
each action. So, original actions implementation is just refactored
using class-based generic view. It is impossible to merge them or share
lots of code.
Fix #193
> Refactor plan and case components action views

- contrib/ansible/testenv/testenv.yml
This fixes the step of checking if PostgreSQL data cluster is already
initialized. Directory /var/lib/pgsql/data exists after
postgresql-server is installed. So, the original way of checking this
directory is not stable.
> Fix testenv playbook

- tcms/core/models/fields.py
- tcms/management/models.py
A customized BooleanField is defined and used for TestBuild.is_active
to allow accepting even true or false from frontend. Django's builtin
BooleanField does not accept 'true' and 'false'.
> Use custom BooleanField for TestBuild.is_active

- tcms/settings/common.py
- tcms/settings/product.py
- remove mention of kerberos b/c users who don't have it get confused
- remove MOTH_AUTH because it is not used at all
Updated:
While reviewing this patch, I'm not quite sure how it is useful for
daily use for users. And showing text in either h2 or h3 seems make no
sense. On the other hand, as what the comment of MOTD_LOGIN says, it
could be good to make it configurable in database so that the messages
can updated easily and no need to restart server to apply the
changes.
So, at this moment, I just update this patch to keep MOTD_LOGIN empty
and leave the decision of what message should be displayed to users who
might find it is useful for his/her use cases.
Signed-off-by: Mr. Senko <atodorov@mrsenko.com>
> Update MOTD_LOGIN setting

- tcms/core/db.py
- tcms/report/data.py
This patch fixes wrong calls to iterator next function and iteritems on
a dict-like object.
> Fix wrong method calls in report data module

- tcms/core/models/base.py
- tcms/core/tests/test_core.py
- tcms/templates/case/get_details_case_run.html
- tcms/templates/mail/edit_case.txt
- tcms/templates/plan/get.html
- tcms/templates/report/custom_details_case_runs.html
- tcms/templates/report/custom_details_status_matrix.html
- tcms/templates/report/testing-report/per_plan_build.html
- tcms/templates/report/testing-report/per_plan_tag.html
- tcms/testcases/models.py
- tcms/testcases/tests/test_models.py
- tcms/testplans/models.py
- tcms/testplans/views.py
- tcms/testruns/models.py
UrlMixin is too old. It can be rewrite in Django builtin functionalities
nowadays. In templates, a get_absolute_url is enough to render the path
part of a model object, and some of URLs can be constructed by using
Site app in the meanwhile.
> Rewrite UrlMixin

- requirements.txt
- setup.py
- tcms/testplans/views.py
So far, django-preserialize does not support Django>=1.11 and project
maintainer does not have time to implement that. Instead of waiting for
someone else to do that, this patch drops django-preserialize as a
for now.
Fixes #311
> Drop django-preserialize

- tcms/testplans/helpers/email.py
- tcms/testplans/tests/test_models.py
This is for signal handlers of a plan update and delete event.
Fixes #316
> Fix a filter call while collecting recipients

- tcms/settings/common.py
- tcms/templates/tcms_base.html
Piwik is not useful for every user. Such service might be used by some
users. It could be added in a more general mechanism in Nitrate. But not
now. If such services are required in real product environment, add it
at that time in the future.
Fixes #323
> Remove Piwik

- tcms/integration/issuetracker/models.py
- tcms/integration/issuetracker/services.py
- tcms/integration/issuetracker/task.py
- tcms/integration/issuetracker/tests/test_models.py
- tcms/settings/common.py
- tcms/settings/product.py
Each issue tracker could have an associated credential, and is
accessible via property ``credential``. Task bugzilla_external_tracker
is fixed with this new credential to pass bugzilla username and
password. Hence, original configs in settings module is not used any
more, which are removed from both common and product settings modules.
> Get issuetracker credential

- tcms/templates/tcms_base.html
SCRIPT tag referencing nonexisting jquery.min.js is removed from base
template.
> Remove reference to nonexisting jquery.min.js

- setup.py
- tox.ini
celery was moved to extra async, and kobo is one of the dependencies
listed in setup.py so it is not necessary to list it again in testenv
deps in tox.ini.
> Remove celery from install_requires and kobo from testenv deps

- src/tcms/core/models/fields.py
> Remove deprecated parameter context from Field.from_db_value

- src/tcms/report/data.py
- src/tcms/report/sqls.py
While generating report "By Case-Run Tester", code sorts subtotal result by
case runs' tester user ID to ensure the order in rendered web page. However, a
test case run could have no default tester, which results in NULL is stored in
database and None is set as corresponding Python object. Hence, the sort fails
on such kind of list [1, 2, 3, None].
To fix this issue, instead of sorting in Python, the subtotal data is sorted in
database level by adding ORDER BY clause to the underlying SQL SELECT
statement.
This error happens when run Nitrate locally with Python 3.6 and PostgreSQL.
Fixes #394
In addition to issue #394, this patch also fixes same issue happening to
generate "By Plan's Tag Per Tag View" report. The solution is same. Just sort
in database by adding ORDER BY clause and avoid …
> Fix incorrect comparison with int and None for sort

- contrib/travis-ci/Dockerfile
- contrib/travis-ci/runtests.sh
- docker/released/Dockerfile
- setup.py
- src/tcms/__init__.py
- src/tcms/core/models/fields.py
Last time to replace MySQLdb-python with PyMySQL, that is because the former
package did not work with Python 3. And nowadays, there is a fork frok named
mysqlclient which works with Python 3 and bug fixes. Django also uses this
library for the mysql database backend.
> Use mysqlclient from now on

- Makefile
- docker-compose.yml
- docker/released/Dockerfile
- docker/released/README.md
docker/released/Dockerfile is refactored to allow building image from version
branch. As a result, once an image is required to be built for a specific
version, just checkout to that version by tag or branch, then `make image'.
Note that, the Dockerfile does not download any tarball from Github anymore.
With this change, it is also possible to build latest image from development
branch. By default, checkout to development branch (currently it is the develop
branch), run `make image', the default tag is 'latest'.
To build an image for a specific version, please remember to set environment
variable IMAGE_VERSION, for example:
make image IMAGE_VERSION=4.3
> Allow building image from version branch

- docker-compose.yml
docker-compose.yml recognizes two environment variables to construct the image
tag, which is same as what are used to `make image'.
* DOCKER_ORG: specifies the prefix of namespace of image in registry. Default
is quay.io/nitrate.
* IMAGE_VERSION: the image version. Default is latest.
So, if to launch the latest Nitrate image, just simply:
docker-compose -f docker-compose.yml up
if to launch container of a specific version:
IMAGE_VERSION=4.3 docker-compose -f docker-compose.yml up
> Parametrize image tag in docker-compose.yml

- src/tcms/core/ajax.py
- src/tests/core/test_views.py
This bug was found when adding a parent plan to a plan which does not have one
yet. In this case, original value of plan's parent is None.
The fix sets a word None to log action original value.
> Save log action properly if original value is None

- src/tcms/testcases/views.py
- src/tcms/xmlrpc/filters.py
- src/tests/__init__.py
- src/tests/core/test_core.py
- src/tests/core/test_views.py
- src/tests/test_management.py
- src/tests/testcases/test_views.py
- src/tests/testplans/test_views.py
- src/tests/testruns/test_views.py
- src/tests/xmlrpc/test_filters.py
- src/tests/xmlrpc/test_product.py
- src/tests/xmlrpc/test_tag.py
- src/tests/xmlrpc/test_testbuild.py
- src/tests/xmlrpc/test_testcaseplan.py
- src/tests/xmlrpc/test_testcaserun.py
- src/tests/xmlrpc/test_testplan.py
- src/tests/xmlrpc/test_user.py
- src/tests/xmlrpc/utils.py
Simplify massive assertions on response status code.
Importing HTTPStatus instead of http.HTTPStatus to shorten lines of
code.
> Clean more code accessing HTTPStatus

- src/tcms/testruns/forms.py
- src/tests/xmlrpc/test_testcaserun.py
clean_assignee does not work as expected since what it does is actually
incorrect. The code creating a test case run via XMLRPC API works
because TestRun.add_case_run sets assignee in the correct way.
Tests are added for testing using test case or test run default tester
as assignee.
> Remove clean_assignee from XMLRPCNewCaseRunForm

- contrib/travis-ci/Dockerfile
Tries to reduce the size of testbox. No packages are cached by pip. Do
not add whole project directory while building image. Remove an
unnecessary RPM.
> Reduce the size of testbox

- src/static/js/tcms_actions.js
This is a regression bug caused by commit bc97bfa.
> Blank select option should have an empty value

- src/tcms/testcases/views.py
request.body is a bytestring. For constructing the data passing to
Javascript in the clinet side, it must be converted into str and written
into template.
> Fix load more tests

- .travis.yml
- requirements.txt
Use new version of coverage 5.x and hack the results in .coverage which
is a SQLite database file.
The testbox image has been updated with coverage 5.x and pushed to
Quay.io.
> Fix failure coverage upload to coveralls

- setup.py
This package is not required after Python 2 was dropped.
> Remove future-breakpoint from devtools

- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
The original intention is the first argument of
constructPlanParentPreviewDialog is not used. By reviewing this function
again, it is no need to keep it anymore since it just calls previewPlan
in a single line of code.
> JS: remove constructPlanParentPreviewDialog

- src/templates/case/edit.html
- src/templates/case/new.html
- src/templates/environment/group_edit.html
- src/templates/plan/edit.html
- src/templates/plan/get.html
- src/templates/plan/new.html
- src/templates/run/edit.html
- src/templates/tcms_base.html
With the last time to fix this location, it causes datatable cannot
loaded properly when accessing the Runs tab in a plan page.
This also adds a missing element ID that make the select filter work
again.
> Fix location to load django jQuery lib

- src/static/js/tcms_actions.js
- src/static/js/testrun_actions.js
- src/tests/js/js-tests.html
- src/tests/js/test-tcms-actions.js
qunit is used by Django to test its JavaScript code. After researching
on qunit, I found out it is so easy to understand and start to write
test code with it and the code can also be organized in a reasonable
structure easily. I'm pretty happy with qunit now. However, followings
are some points to be researched:
* mock jQuery.ajax.
* better run tests from command line in order to integrate it with CI
process.
* show and inspect JavaScript code coverage.
Better than nothing at this moment. Just open the js-tests.html in a Web
browser and tests will run.
> JS: start to test js code with qunit

- src/tcms/auth/views.py
- src/tcms/core/files.py
- src/tcms/core/views/__init__.py
- src/tcms/core/views/prompt.py
- src/tcms/testcases/views.py
- src/tcms/testplans/views.py
- src/tcms/testruns/views.py
- src/templates/prompt.html
- src/tests/core/test_files.py
The prompt render is reimplemented in a much simpler way by providing
two functions for different levels. The code Prompt.render are updated
with the new functions accordingly.
Relative to #449
> Simplify Prompt.render

- setup.py
- src/tests/core/test_core.py
Fixes #457
At this moment, version 4.3 is an old version. So, just skip it and upgrade to version 4.4.
> Upgrade celery to 4.4

- src/static/js/advance_search.js
- src/static/js/deleconfirm.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/tcms/comments/views.py
- src/templates/case/get_issues.html
- src/tests/test_comments.py
There are two kinds of jQuery.ajax calls. One is to make a JSON request
which expects the server side responses data in JSON format. And another
one is to just make a normal HTTP request and server responses a piece
of HTML. These calls are abstracted into two dedicated functions which
contains some default values and behavior, which simpifies the original
calls to jQuery.ajax.
Fixes #604
> JS: abstract jQuery.ajax calls

- src/templates/run/get_case_runs.html
This change enforces to press OK button explicitly to add an issue key
to a case run.
> Avoid submitting issue key when press enter

- .travis.yml
- Makefile
- contrib/travis-ci/Dockerfile
So, enable the docker-pull again before running tests inside.
> Allow to specify alternative PyPI index to build testbox

- setup.py
This is helpful to suppress warning message emit from psycopg2. As
mentioned in the message, for relative info about the warning, refer to
https://www.psycopg.org/docs/install.html#binary-install-from-pypi
> Use new package name psycopg2-binary

- src/static/js/lib/jquery.shiftcheckbox.js
- src/static/js/management_actions.js
- src/static/js/profiles.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/templates/case/common/case_advance_filtered.html
- src/templates/case/common/case_filtered.html
- src/templates/case/get_component.html
- src/templates/plan/cases_rows.html
- src/templates/plan/common/plans_advance_filtered.html
- src/templates/plan/common/plans_filtered.html
- src/templates/plan/get_cases.html
- src/templates/plan/get_component.html
- src/templates/plan/get_review_cases.html
- src/templates/plan/get_runs.html
- src/templates/plan/search_case.html
- src/templates/profile/bookmarks.html
- src/templates/run/common/run_advance_filtered.html
- src/templates/run/common/run_filtered.html
- src/templates/run/table_caseruns.html
- src/templates/search/runs.html
Upgrade this plugin to the latest version in upstream and enable it for
tables.
Meanwhile, some relative code are refactored to simplify the implement
the select all and enable/disable related buttons according the checked
status.
Fixes #660
> JS: Upgrade jquery.shiftcheckbox and enable it

- src/tcms/auth/apps.py
- src/tcms/auth/forms.py
- src/tcms/comments/apps.py
- src/tcms/comments/forms.py
- src/tcms/core/apps.py
- src/tcms/core/forms/fields.py
- src/tcms/profiles/forms.py
- src/tcms/search/views.py
- src/tcms/xmlrpc/apps.py
Suppress warning:
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is
deprecated in favor of django.utils.translation.gettext_lazy().
Fixes #637
> Use gettext_lazy

- setup.py
This change will make it easier to follow up with upstream latest
releases. Meanwhile, it is also helpful for building and installing
Nitrate in specific Linux distribution, for example building RPM package
and install on Fedora.
> Do not limit some requirements on specific version

- docker/released/Dockerfile
Build the release image by installing nitrate from built RPM package.
> Simplify release image Dockerfile

- contrib/conf/nitrate-httpd.conf
- contrib/conf/wsgi-venv.conf
- docker/released/Dockerfile
- python-nitrate-tcms.spec
- src/tcms/wsgi.py
* Remove unnecessary code and commented out lines from wsgi.py
* Since Nitrate has been Python 3 only already, remove mod_wsgi from
SPEC file. mod_auth_gssapi is removed as well. The deployment
artifacts, e.g. the Dockerfile, should be the right place to install
required packages.
* Use mysqlclient rather than pymysql in SPEC which was replaced in the
Python distribution already.
* Install missing python3-mod_wsgi in Dockerfile
* It is also fixed to copy product.py to right settings directory in
Dockerfile.
* Delete wsgi-venv.conf and merge its content into nitrate-httpd.conf
directly. python-home is removed since Nitrate is not installed into a
virtual environment in the container, and the path of wsgi.py is also
fixed accordingly.
* Remove COPY of wsgi-venv.conf from Dockerfile. …
> Fix to make Nitrate run well in release container

- src/static/js/tcms_actions.js
- src/static/js/testplan_actions.js
- src/templates/plan/get_cases.html
- src/templates/plan/get_review_cases.html
This patch simplifies the event handler calls in plan's cases details
pane by moving the handler code into constructPlanDetailsCasesZone
directly. It looks the function is too big, however it reduces the
function calls by passing arguments through several levels. In practice,
it will be much easier to understand the event handlers.
> JS: simplify the event handlers in plan cases details pane

- docker/dev/Dockerfile
python-bugzilla finds executable rst2man or rst2man.py. During the image
build, that executable will be available only when the venv is activated.
> Activate venv during dev image build

- src/tcms/testplans/models.py
- src/tcms/testplans/views.py
- src/tests/testplans/test_models.py
- src/tests/testplans/test_views.py
The new plan could be created by creating a new plan or cloning an
existing plan.
> Set email_settings to new plan (#737)

- src/tcms/search/views.py
In advanced search result page, query arguments are removed incorrectly,
that causes error when clicking a paging button.
> Fix wrong query string in paging buttons (#731)

- src/tcms/core/db.py
- src/tcms/report/data.py
- src/tests/core/test_core.py
Raise KeyError if key does not exist in the _data. This is for making
GroupByResult to be a real dict-like object.
> Fix GroupByResult.__getitem__ (#772)

- src/templates/menu.html
For example a user has email a+b@example.com, without this encode,
'a+b@example.com' will be present in the URL querystring, and then the
email address will be in the textbox as 'a b@example.com' eventually.
> Encode author email in My Plans querystring (#262)

- src/tcms/core/files.py
It's strange, six is still imported in this file. Is it not covered by
tests, or the test environment is not provisioned properly inside which
six is installed accidentially? Not sure. Anyway, remove it and replaced
with Python 3 urllib.parse.unquote.
> Remove six module from files.py

- src/static/js/comment.js
- src/static/js/tcms_actions.js
- src/static/js/testrun_actions.js
- src/templates/case/get_details_case_run.html
- src/templates/run/get_case_runs.html
- src/tests/testcases/test_views.py
The original problem is a regression bug that is when a case run related
data is changed, for example adding a comment, the code will find all
elements which have class .expandable and trigger the click to load
those details. In addition, the original behavior before this regression
the case run detail endpoint was requested twice in order to reload the
detail.
This patch refactors the relative codebase a lot to reload the
detail only once. The relative behaviors are:
* change case run status
* add a comment to a case run
* remove a comment to a case run
* add an issue to a case run
* remove an issue from a case run
* add a link to a case run
This patch also fixes a bug that is to update the number of issues to
the case run row.
> JS: reload case run detail pane only once

- src/static/style/base.css
This is a regression just found. Every case run's status button should
be in gray color to reflect the disabled status.
> Fix case run status button CSS style for disabled

- src/static/js/management_actions.js
The request URL is got from form action incorrectly. That causes the
global CSRF token cannot be read and set into the request header.
> JS: fix error when save an environment group

- src/tcms/report/data.py
- src/tcms/report/views.py
- src/tests/test_report.py
- src/tests/test_search.py
If a product has not either plan, case or run, get the default value 0
from statistics correctly to generate the report.
> Fix report overall

- src/static/js/testrun_actions.js
This is actually a regression bug. Restore the original behavior.
> JS: allow to change case run status without comment

- .eslintrc.js
- src/static/js/nitrate.toggledetail.js
- src/static/js/tcms_actions.js
- src/static/js/testcase_actions.js
- src/static/js/testplan_actions.js
- src/static/js/testrun_actions.js
- src/templates/case/all.html
- src/templates/case/get.html
- src/templates/case/get_details_case_case_run.html
- src/templates/plan/choose_testrun.html
- src/templates/plan/get.html
- src/templates/run/assign_case.html
- src/templates/run/clone.html
- src/templates/run/get.html
- src/templates/run/new.html
- src/templates/search/results.html
- src/tests/testruns/test_views.py
Detail expansion involves expanding case detail, expanding case run
detail and expanding a plan's case runs under a case. Lots of duplicate
code handles that various detail expansions. All of them have similar
logic and almost same HTML structure rendered from templates. Years
later, such situation makes it difficult to maintain those code.
This patch removes those duplicate code by organizing them into
dedicated classes and unify all the things in a well-structured
JavaScript code base and templates.
> JS: refactor detail expansion

- .github/workflows/dev-release.yaml
By default, actions/checkout does not fetch tags, then git-describe
fails to output the result.
> Fetch all history in order to run git-describe

- src/tcms/core/apps.py
Since django-contrib-comments version 2.1.0, the object_pk is altered
to a CharField with a fixed length. There is no need to change this
field type to int by Nitrate itself, otherwise, the migrations conflict.
The new type should work.
> Do not alter comment model's object_pk data type

- contrib/compose/web_custom_conf.py
When run locally inside container, the email backend is not
pre-configured and ready-for-use. This causes Nitrate raises 500 error
when sending email notification. Using dummy email backend makes things
easy and user is able to change it to a real email backend along with
setting other EMAIL_* settings.
> Use dummy email backend for local run inside container

- src/tcms/core/ajax.py
The type User cannot be serialized to JSON when schedule the mailto
asynchronous task. The change works for rendering corresponding template
that just renders the user's name.
> Fix mailto task argument user type

- .readthedocs.yml
> Missing path in the python.install in rtd config

- src/static/js/tcms_actions.js
- src/templates/csrf.html
- src/templates/tcms_base.html
This change also removes the need of jQuery.
closes: #1031
> JS: call a function to get the AJAX CSRF token (#1031)

- tox.ini
src/tests/ is not hardcoded in testenv.
> Allow to specify test module for tox testenv

- src/tcms/testruns/models.py
- src/tcms/testruns/views.py
- src/tests/testruns/test_views.py
This method was removed incorrectly that causes editing a test run will
fail if Set Status Automatically is checked.
> Recover completed_case_run_percent

- .github/workflows/unittests.yaml
- README.rst
- docs/source/index.rst
- setup.cfg
- tox.ini
> Remove Django 3.1 from testenv (#1077)

- src/tcms/settings/test.py
According to /topics/testing/overview/#password-hashing, this is a
faster way to run tests and actually it is, really!
> Use md5 password hasher for tests

- src/tcms/settings/common.py
This is introduced in Django 3.2 and is required in settings or warnings
will be printed as:
testruns.TestRunTag: (models.W042) Auto-created primary key used when
not defining a primary key type, by default
'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the
AppConfig.default_auto_field attribute to point to a subclass of
AutoField, e.g. 'django.db.models.BigAutoField'.
The BugAutoField will be applied to a new generated database. By a quick
testing, no need to update the existing database, no migration there.
Hopefully, everything works well as normal with this change.
> Add new setting DEFAULT_AUTO_FIELD

- src/tcms/core/utils.py
- src/tests/core/test_core.py
mccabe reports timedelta2int is too complexity. This patch fixes that.
> Simplify timedelta2int

- src/tcms/core/utils.py
Using found_units instead of iterating delta parts to check if any d, h,
m or s presents in the input.
> Refine timedelta2int

- src/tcms/urls.py
If 'SOCIAL' is an enabled AUTH Backend, the
social_django.urls must be added to the url_patterns
Fixes #1095 / Closes #1095
> Bugfix: Add django social app

- src/tcms/testruns/views.py
- tests/testruns/test_views.py
The original message could confuse user as it is not clear whether the update operation succeeds or not. The reported issue actually is not a problem that something fails. With the new message, it should be clear to user what just happened.
> Reword message for updating case runs (#1036)
